import type { GalleryImage, GalleryResponse } from "../../lib/api/noofyApi";

/**
 * Placeholder thumbnail URLs using picsum.photos (deterministic by seed).
 * Replace with real Noofy output URLs once the backend endpoint exists.
 */
function picsum(seed: number, w = 512, h = 512) {
  return `https://picsum.photos/seed/${seed}/${w}/${h}`;
}

export const MOCK_GALLERY_IMAGES: GalleryImage[] = [
  {
    id: "img-001",
    thumbnailUrl: picsum(10, 400, 400),
    imageUrl: picsum(10, 1024, 1024),
    workflowId: "text_to_image_v0",
    workflowName: "Text to Image",
    prompt: "a snowy mountain range at golden hour, cinematic lighting",
    createdAt: "2026-04-30T14:22:00Z",
    width: 1024,
    height: 1024,
    favorite: true,
    usedSettings: {
      Prompt: "a snowy mountain range at golden hour, cinematic lighting",
      Style: "Photorealistic",
      "Aspect ratio": "1:1",
      "Variation ID": "42",
      "Detail passes": 30,
      "Prompt strength": 7.5,
    },
    fileRef: "outputs/2026-04-30/img-001.png",
  },
  {
    id: "img-002",
    thumbnailUrl: picsum(22, 400, 400),
    imageUrl: picsum(22, 1024, 1024),
    workflowId: "text_to_image_v0",
    workflowName: "Text to Image",
    prompt: "a cozy cafe interior on a rainy day, warm tones",
    createdAt: "2026-04-30T16:05:00Z",
    width: 1024,
    height: 1024,
    favorite: false,
    usedSettings: {
      Prompt: "a cozy cafe interior on a rainy day, warm tones",
      Style: "Cinematic",
      "Aspect ratio": "1:1",
      "Variation ID": "7",
      "Detail passes": 25,
      "Prompt strength": 7.0,
    },
    fileRef: "outputs/2026-04-30/img-002.png",
  },
  {
    id: "img-003",
    thumbnailUrl: picsum(37, 400, 400),
    imageUrl: picsum(37, 1024, 1024),
    workflowId: "text_to_image_v0",
    workflowName: "Text to Image",
    prompt: "an astronaut floating above Earth at sunrise",
    createdAt: "2026-04-29T09:41:00Z",
    width: 1024,
    height: 1024,
    favorite: false,
    usedSettings: {
      Prompt: "an astronaut floating above Earth at sunrise",
      Style: "Photorealistic",
      "Aspect ratio": "1:1",
      "Variation ID": "101",
      "Detail passes": 30,
      "Prompt strength": 8.0,
    },
    fileRef: "outputs/2026-04-29/img-003.png",
  },
  {
    id: "img-004",
    thumbnailUrl: picsum(55, 400, 400),
    imageUrl: picsum(55, 1024, 1024),
    workflowId: "text_to_image_v0",
    workflowName: "Text to Image",
    prompt: "a serene Japanese garden in autumn, koi pond",
    createdAt: "2026-04-29T11:18:00Z",
    width: 1024,
    height: 1024,
    favorite: true,
    usedSettings: {
      Prompt: "a serene Japanese garden in autumn, koi pond",
      Style: "Painterly",
      "Aspect ratio": "1:1",
      "Variation ID": "200",
      "Detail passes": 28,
      "Prompt strength": 6.5,
    },
    fileRef: "outputs/2026-04-29/img-004.png",
  },
  {
    id: "img-005",
    thumbnailUrl: picsum(68, 400, 400),
    imageUrl: picsum(68, 1024, 1024),
    workflowId: "text_to_image_v0",
    workflowName: "Text to Image",
    prompt: "a neon-lit street market at night in Hong Kong",
    createdAt: "2026-04-28T20:30:00Z",
    width: 1024,
    height: 1024,
    favorite: false,
    usedSettings: {
      Prompt: "a neon-lit street market at night in Hong Kong",
      Style: "Photorealistic",
      "Aspect ratio": "1:1",
      "Variation ID": "33",
      "Detail passes": 30,
      "Prompt strength": 7.5,
    },
    fileRef: "outputs/2026-04-28/img-005.png",
  },
  {
    id: "img-006",
    thumbnailUrl: picsum(79, 400, 400),
    imageUrl: picsum(79, 1024, 1024),
    workflowId: "text_to_image_v0",
    workflowName: "Text to Image",
    prompt: "a medieval castle perched on a cliff over the sea",
    createdAt: "2026-04-28T15:00:00Z",
    width: 1024,
    height: 1024,
    favorite: false,
    usedSettings: {
      Prompt: "a medieval castle perched on a cliff over the sea",
      Style: "Digital art",
      "Aspect ratio": "1:1",
      "Variation ID": "9",
      "Detail passes": 22,
      "Prompt strength": 7.0,
    },
    fileRef: "outputs/2026-04-28/img-006.png",
  },
  {
    id: "img-007",
    thumbnailUrl: picsum(91, 400, 400),
    imageUrl: picsum(91, 1024, 1024),
    workflowId: "text_to_image_v0",
    workflowName: "Text to Image",
    prompt: "a lone wolf howling at a full moon, dramatic sky",
    createdAt: "2026-04-27T22:10:00Z",
    width: 1024,
    height: 1024,
    favorite: true,
    usedSettings: {
      Prompt: "a lone wolf howling at a full moon, dramatic sky",
      Style: "Cinematic",
      "Aspect ratio": "1:1",
      "Variation ID": "88",
      "Detail passes": 30,
      "Prompt strength": 8.0,
    },
    fileRef: "outputs/2026-04-27/img-007.png",
  },
  {
    id: "img-008",
    thumbnailUrl: picsum(105, 400, 400),
    imageUrl: picsum(105, 1024, 1024),
    workflowId: "text_to_image_v0",
    workflowName: "Text to Image",
    prompt: "a futuristic city skyline at dusk, flying vehicles",
    createdAt: "2026-04-27T18:45:00Z",
    width: 1024,
    height: 1024,
    favorite: false,
    usedSettings: {
      Prompt: "a futuristic city skyline at dusk, flying vehicles",
      Style: "Concept art",
      "Aspect ratio": "1:1",
      "Variation ID": "512",
      "Detail passes": 35,
      "Prompt strength": 7.5,
    },
    fileRef: "outputs/2026-04-27/img-008.png",
  },
  {
    id: "img-009",
    thumbnailUrl: picsum(117, 400, 400),
    imageUrl: picsum(117, 1024, 1024),
    workflowId: "text_to_image_v0",
    workflowName: "Text to Image",
    prompt: "a still life with fresh flowers and morning light",
    createdAt: "2026-04-26T09:00:00Z",
    width: 1024,
    height: 1024,
    favorite: false,
    usedSettings: {
      Prompt: "a still life with fresh flowers and morning light",
      Style: "Painterly",
      "Aspect ratio": "1:1",
      "Variation ID": "14",
      "Detail passes": 25,
      "Prompt strength": 6.0,
    },
    fileRef: "outputs/2026-04-26/img-009.png",
  },
  {
    id: "img-010",
    thumbnailUrl: picsum(130, 400, 400),
    imageUrl: picsum(130, 1024, 1024),
    workflowId: "text_to_image_v0",
    workflowName: "Text to Image",
    prompt: "deep ocean bioluminescent creatures, dark water",
    createdAt: "2026-04-25T13:30:00Z",
    width: 1024,
    height: 1024,
    favorite: false,
    usedSettings: {
      Prompt: "deep ocean bioluminescent creatures, dark water",
      Style: "Photorealistic",
      "Aspect ratio": "1:1",
      "Variation ID": "77",
      "Detail passes": 30,
      "Prompt strength": 7.5,
    },
    fileRef: "outputs/2026-04-25/img-010.png",
  },
  {
    id: "img-011",
    thumbnailUrl: picsum(143, 400, 400),
    imageUrl: picsum(143, 1024, 1024),
    workflowId: "text_to_image_v0",
    workflowName: "Text to Image",
    prompt: "an ancient Roman street scene at midday, marble columns",
    createdAt: "2026-04-24T11:20:00Z",
    width: 1024,
    height: 1024,
    favorite: false,
    usedSettings: {
      Prompt: "an ancient Roman street scene at midday, marble columns",
      Style: "Photorealistic",
      "Aspect ratio": "1:1",
      "Variation ID": "303",
      "Detail passes": 30,
      "Prompt strength": 7.5,
    },
    fileRef: "outputs/2026-04-24/img-011.png",
  },
  {
    id: "img-012",
    thumbnailUrl: picsum(158, 400, 400),
    imageUrl: picsum(158, 1024, 1024),
    workflowId: "text_to_image_v0",
    workflowName: "Text to Image",
    prompt: "a watercolor painting of Paris in the rain",
    createdAt: "2026-04-23T17:55:00Z",
    width: 1024,
    height: 1024,
    favorite: true,
    usedSettings: {
      Prompt: "a watercolor painting of Paris in the rain",
      Style: "Watercolor",
      "Aspect ratio": "1:1",
      "Variation ID": "6",
      "Detail passes": 20,
      "Prompt strength": 6.5,
    },
    fileRef: "outputs/2026-04-23/img-012.png",
  },
];

export const MOCK_GALLERY_RESPONSE: GalleryResponse = {
  images: MOCK_GALLERY_IMAGES,
  total: MOCK_GALLERY_IMAGES.length,
};
